apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rstudios.emmaliaocode.dev
spec:
  scope: Namespaced
  group: emmaliaocode.dev
  names:
    kind: Rstudio
    plural: rstudios
    singular: rstudio
    shortNames:
      - rst
      - rsts
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            description: "Specification of the Rstudio instance."
            type: object
            properties:
              image:
                description: "Image digest from Docker Hub (rocker/rstudio). Must start with the prefix rocker/rstudio and separate the R version with `:`. For example, `rocker/rstudio:4.4.0` creates an Rstudio of R version 4.4.0."
                type: string
              imagePullPolicy:
                description: "Image pull policy. One of `Always`, `Never`, `IfNotPresent`. Defaults to `Always` if the 'latest' tag is specified in image, or `IfNotPresent` otherwise."
                type: string
                enum:
                - Always
                - IfNotPresent
                - Never
              loginSecret:
                description: "Set the password for logining to Rstudio with a Secret, the secret must contain a `password` key. Default password will be printed in the container log if this is not set."
                type: string
              isRoot:
                description: "Whether the Linux system user should be added to the sudoers group during the Rstudio server init process. Default is `false`."
                type: boolean
                default: false
              resources:
                description: "Compute Resources required by this Rstudio instance."
                type: object
                properties:
                  requests:
                    description: "Requests describes the minimum amount of compute resources required."
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    description: "Limits describes the maximum amount of compute resources allowed."
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
              storages:
                description: "Storages are a list of claims that an Rstudio instance is allowed to reference."
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: "Name of the claim."
                      type: string
                    storageClassName:
                      description: "Name of the StorageClass required by the claim."
                      type: string
                    storageSize:
                      description: "StorageSize represents the minimum resources the volume should have."
                      type: string
                    accessModes:
                      description: "AccessModes contains the desired access modes the volume should have. Could be `ReadWriteOnce`, `ReadOnlyMany`, `ReadWriteMany`."
                      type: array
                      items:
                        type: string
                        enum:
                        - ReadWriteOnce
                        - ReadOnlyMany
                        - ReadWriteMany
                  required:
                  - name
                  - storageSize
                  - accessModes
              volumes:
                description: "Volumes that can be mounted to the Rstudio instance."
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: "Name of the volume must be unique."
                      type: string
                    configMap:
                      description: "Mount a ConfigMap that already existed in the same namespace."
                      type: object
                      properties:
                        name:
                          description: "Name of the referent."
                          type: string
                        items:
                          description: "Items if unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present."
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                description: "Key is the key to project."
                                type: string
                              path:
                                descriptions: "Path is the relative path of the file to map the key to."
                                type: string
                            required:
                            - key
                            - path
                      required:
                      - name
                    persistentVolumeClaim:
                      description: "Mount a PersistentVolumeClaim that already existed in the same namespace."
                      type: object
                      properties:
                        claimName:
                          description: "ClaimName is the name of a PersistentVolumeClaim in the same namespace as the pod using this volume."
                          type: string
                      required:
                      - claimName
                    secret:
                      description: "Mount a Secret that already existed in the same namespace."
                      type: object
                      properties:
                        secretName:
                          description: "SecretName is the name of the secret in the pod's namespace to use."
                          type: string
                      required:
                      - secretName
                    emptyDir:
                      description: "EmptyDir represents a temporary directory that shares a pod's lifetime."
                      type: object
                      properties:
                        sizeLimit:
                          descriptions: "SizeLimit is the total amount of local storage required for this EmptyDir volume. The size limit is also applicable for memory medium. The maximum usage on memory medium EmptyDir would be the minimum value between the SizeLimit specified here and the sum of memory limits of all containers in a pod. The default is nil which means that the limit is undefined."
                          type: string
                  required:
                  - name
              volumeMounts:
                description: "Volumes to mount into the container's filesystem."
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: "This must match the Name of a Volume."
                      type: string
                    mountPath:
                      description: "Path within the container at which the volume should be mounted. Must not contain ':'."
                      type: string
            required:
            - image
          status:
            description: "Most recently observed status of the Rstudio."
            x-kubernetes-preserve-unknown-fields: true
        required:
        - apiVersion
        - kind
        - metadata
        - spec
