apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rstudios.emmaliaocode.dev
spec:
  scope: Namespaced
  group: emmaliaocode.dev
  names:
    kind: Rstudio
    plural: rstudios
    singular: rstudio
    shortNames:
      - rst
      - rsts
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            description: Spec defines the desired state of RStudio.
            type: object
            properties:
              image:
                description: Image digest selected from DockerHub (https://hub.docker.com/r/rocker/rstudio/tags). The tag of the image refers to the R version.
                type: string
              imagePullPolicy:
                description: Policy of the Kubelet to pull an image, default is IfNotPresent.
                type: string
                default: IfNotPresent
                enum:
                - Always
                - IfNotPresent
                - Never
              loginPassword:
                description: Password with Base64 encoded for login to RStudio.
                type: string
            required:
            - image
            - loginPassword
          status:
            description: Status and results of the rstudio resource.
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
