apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rstudios.emmaliaocode.dev
spec:
  scope: Namespaced
  group: emmaliaocode.dev
  names:
    kind: Rstudio
    plural: rstudios
    singular: rstudio
    shortNames:
      - rst
      - rsts
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            description: "Defines the desired state of RStudio."
            type: object
            properties:
              image:
                description: "Image digest selected from DockerHub, the tag of the image refers to the R version."
                type: string
              imagePullPolicy:
                description: "Policy of the Kubelet to pull an image, default is IfNotPresent."
                type: string
                default: IfNotPresent
                enum:
                - Always
                - IfNotPresent
                - Never
              loginSecret:
                description: "Secret that contains a key 'password' for login to RStudio."
                type: string
              isRoot:
                description: "Whether the Linux system user `rstudio` should be added to the `sudoers` group during the RStudio server init process, default is False."
                type: boolean
              resources:
                description: "Compute Resources required by this container. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/. ResourceRequirements describes the compute resource requirements."
                type: object
                properties:
                  requests:
                    description: "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/. Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and AsInt64() accessors."
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    description: "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/. Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and AsInt64() accessors."
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
            required:
            - image
            - isRoot
          status:
            description: "Status and results of the rstudio resource."
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
