---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rstudio-operator-serviceaccount
  namespace: "{namespace}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rstudio-operator-clusterrole
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: ["list", "watch"]
  - apiGroups: ["emmaliaocode.dev"]
    resources: ["rstudios"]
    verbs: ["get", "list", "watch", "create", "remove", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "remove", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "events"]
    verbs: ["get", "list", "watch", "create", "remove", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rstudio-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rstudio-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: rstudio-operator-serviceaccount
    namespace: "{namespace}"
