apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rstudios.emmaliaocode.dev
spec:
  scope: Namespaced
  group: emmaliaocode.dev
  names:
    kind: Rstudio
    plural: rstudios
    singular: rstudio
    shortNames:
      - rst
      - rsts
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
          status:
            x-kubernetes-preserve-unknown-fields: true
