apiVersion: emmaliaocode.dev/v1
kind: Rstudio
metadata:
  name: example
  namespace: default
spec:
  image: rocker/rstudio:4.4.0
  imagePullPolicy: IfNotPresent
  loginSecret: rstudio-secret
  isRoot: true
  resources:
    requests:
      cpu: "250m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"
  storages:
  - name: my-storage
    storageClassName: standard
    storageSize: "1Gi"
    accessModes:
    - ReadWriteMany
  volumes:
  - name: my-config
    configMap:
      name: my-config
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-pvc
  - name: my-secret
    secret:
      secretName: my-secret
  - name: my-empty-dir
    emptyDir:
      sizeLimit: "1Gi"
  volumeMounts:
  - name: my-storage
    mountPath: /storage
  - name: my-config
    mountPath: /config
  - name: my-pvc
    mountPath: /pvc
  - name: my-secret
    mountPath: /secret
  - name: my-empty-dir
    mountPath: /empty-dir
