apiVersion: emmaliaocode.dev/v1
kind: Rstudio
metadata:
  name: example
  namespace: default
spec:
  image: rocker/rstudio:latest
  imagePullPolicy: IfNotPresent
  loginSecret: rstudio-secret
  isRoot: true
  resources:
    requests:
      cpu: "250m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"
  storages:
  - name: rstudio-pvc
    storageClassName: standard
    storageSize: "1Gi"
    accessModes:
    - "ReadWriteMany"
  volumes:
  - name: parameters
    configMap:
      name: parameters-cm
  volumeMounts:
  - name: rstudio-pvc
    mountPath: /data
  - name: parameters
    mountPath: /params
